### ISSUE TITLE
혹시 지금 maxtime이 17인데 20으로 바꾸고 싶다면 어떤것들을 바꿔야 할까요??

### ISSUE THREAD

**Issue by kimchidad** [della-padula/Elliotable#28]
지금 한번 만들어보고 있는 앱중에 저희 학교 timetable에 맞게 사용해보고있습니다.
일단 이런 library를 만들어 주셔서 정말 정말 감사합니다.
근데 이제 지금 상태에선 오후 5시까지밖에 클래스가 에드가 안되는데 만약 table를 20시나 21시 까지 늘리고 싶다면 어떤것들을 바꿔야할까요??

**Comment by della-padula** [comment]
안녕하세요 관심 감사드립니다 구현 할때에 강의를 새로 추가하면 바로 바뀌도록 구현을 하긴 했는데 course item을 바로 추가하더라도 시간표가 적용이 안되는 현상이 있는건가요??

**Comment by della-padula** [comment]
아직 제가 회사에 있어서 퇴근하고 혹시 모르니 살펴보도록 하겠습니다. 이슈 다시 한 번 감사드립니다.

**Comment by kimchidad** [comment]
단지 시간표를 오후 5시까지가 아니라 오후 9시 혹은 10시 까지로 늘리고싶어서요~ 근데 단지 max시간을 17에서 21이나 22로 늘린다고 풀리는 문제가 아니더라고요... 저가 아직 완전 쌩초보라 아직까진 모든것에 익숙하진 않습니다..ㅠㅠㅠ 그래서 사실 제가 맞는것을 물어 보고있는건지도 확실하지 않네요ㅠㅠㅠ 죄송합니다

**Comment by della-padula** [comment]
현재 구현된 상태로는 그냥 기본적으로 시간표가 보여지는 범위가 09-17시까지입니다 범위를 늘리려면 17시이후로 끝나는 강의를 추가해보시면 될 것 같아요!

**Comment by kimchidad** [comment]
감사합니다!! 코드 하나씩 좀더 자세히 읽어보겠습니다! 그리고 정말 죄송하지만 하나만 더여쭐수있다면 저가 이제 막 swift에 대해 공부를 하기 시작한 학생인데 지금까지 이렇게 library 및 앱을 develop하기 까지 많은 경험가 공부를 하셨을꺼라 생각합니다. 저는 이제 막 하기 시작했는데 사실 유튜브에서 보고 배운거는 저가 앱을 하나 만드랴고 하다보니 밑천이 들어나더라고요. 혹시 실례가 안된다면 swift를 어떻게 배우셨는지 좀더 효과적으로 배울수있는 방법을 여쭤 볼 수 있을까요????

**Comment by della-padula** [comment]
저는 처음에는 꼼꼼한 재은씨 스위프트를 정독하면서 입문을 했었고 Apple Documentation과 Swift 공식 문서를 바탕으로 공부를 했어요. 그러면서 다양하게 프로젝트를 해보면서 경험을 쌓고.. 좀 더 나은 아키텍처는 없을까 끊임 없이 고민을 하고 왜?라는 질문을 많이 던지면서 공부를 했던 것 같아요 :)

**Comment by kimchidad** [comment]
정말 정말 감사합니다!! 좋은 자료 만들어 주셔서 감사해요~ ㅎㅎ
